{
  "_args": [
    [
      {
        "raw": "fs-exists@*",
        "scope": null,
        "escapedName": "fs-exists",
        "name": "fs-exists",
        "rawSpec": "*",
        "spec": "*",
        "type": "range"
      },
      "C:\\VikingSTuff\\projects\\assignment_async_nodejs\\node_modules\\fsp"
    ]
  ],
  "_from": "fs-exists@*",
  "_id": "fs-exists@0.1.1",
  "_inCache": true,
  "_location": "/fs-exists",
  "_npmUser": {
    "name": "meryn",
    "email": "merynstol@gmail.com"
  },
  "_npmVersion": "1.2.18",
  "_phantomChildren": {},
  "_requested": {
    "raw": "fs-exists@*",
    "scope": null,
    "escapedName": "fs-exists",
    "name": "fs-exists",
    "rawSpec": "*",
    "spec": "*",
    "type": "range"
  },
  "_requiredBy": [
    "/fsp"
  ],
  "_resolved": "https://registry.npmjs.org/fs-exists/-/fs-exists-0.1.1.tgz",
  "_shasum": "a0126762c5e9416a3dde695891ceb5e29fc7e133",
  "_shrinkwrap": null,
  "_spec": "fs-exists@*",
  "_where": "C:\\VikingSTuff\\projects\\assignment_async_nodejs\\node_modules\\fsp",
  "author": {
    "name": "Meryn Stol",
    "email": "merynstol@gmail.com"
  },
  "bugs": {
    "url": "https://github.com/meryn/fs-exists/issues"
  },
  "dependencies": {},
  "description": "Wraps fs.exists so callback is called with (err, result).",
  "devDependencies": {
    "async": "~0.2.6",
    "coffee-script": "~1.6.2",
    "mocha": "~1.9.0"
  },
  "directories": {},
  "dist": {
    "shasum": "a0126762c5e9416a3dde695891ceb5e29fc7e133",
    "tarball": "https://registry.npmjs.org/fs-exists/-/fs-exists-0.1.1.tgz"
  },
  "engines": {
    "node": "0.10.x",
    "npm": "1.2.x"
  },
  "homepage": "https://github.com/meryn/fs-exists",
  "keywords": [],
  "main": "lib/fs-exists.js",
  "maintainers": [
    {
      "name": "meryn",
      "email": "merynstol@gmail.com"
    }
  ],
  "name": "fs-exists",
  "optionalDependencies": {},
  "private": false,
  "readme": "# fs-exists [![Build Status](https://travis-ci.org/meryn/fs-exists.png?branch=master)](https://travis-ci.org/meryn/fs-exists)\n\nWraps Node.js' native `fs.exists` so callback is called with `(err, result)` instead of just `(result)`.  \nSince it's just wrapping `fs.exists`, the `err` argument will always be `null`.\n\nI developed the module to have a function that can be easily adapted to return a promise (for example with `faithful.adapt` from my [Faithful](https://github.com/meryn/faithful) project), but you may find other uses for it.\n\n## Usage\n\n```javascript\nfsExists = require('fs-exists')\nfsExists(path, function(err, result) {\n  if (err) throw err; // err will always be null\n  if(result)\n    console.log \"the entry exists\"\n  else\n    console.log \"the entry does not exist\"\n})\n```\n\n## License\n\nfs-exists is released under the [MIT License](http://opensource.org/licenses/MIT).  \nCopyright (c) 2013 Meryn Stol  ",
  "readmeFilename": "README.md",
  "repository": {
    "type": "git",
    "url": "git://github.com/meryn/fs-exists.git"
  },
  "scripts": {
    "prepublish": "npm test",
    "pretest": "make build",
    "test": "make test"
  },
  "version": "0.1.1",
  "warnings": [
    {
      "code": "ENOTSUP",
      "required": {
        "node": "0.10.x",
        "npm": "1.2.x"
      },
      "pkgid": "fs-exists@0.1.1"
    }
  ]
}
